test = {   'name': 'q1_3',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> ',' in with_commas\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> ',' not in without_commas\nTrue", 'hidden': False, 'locked': False},
                                   {'code': '>>> len(with_commas)\n24', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(without_commas)\n22', 'hidden': False, 'locked': False},
                                   {'code': ">>> with_commas == 'Eats, Shoots, and Leaves'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> without_commas == 'Eats Shoots and Leaves'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
