test = {   'name': 'q2_2',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> elements_of_some_numbers.column(0).item(2)\n'third'", 'hidden': False, 'locked': False},
                                   {'code': ">>> elements_of_some_numbers.column(0).item(3)\n'fourth'", 'hidden': False, 'locked': False},
                                   {'code': '>>> elements_of_some_numbers.column(1).item(0)\n0', 'hidden': False, 'locked': False},
                                   {'code': '>>> elements_of_some_numbers.column(1).item(3)\n3', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
