test = {   'name': 'q3_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> first_product\n6594', 'hidden': False, 'locked': False},
                                   {'code': '>>> second_product\n-663168', 'hidden': False, 'locked': False},
                                   {'code': '>>> third_product\n66603205994', 'hidden': False, 'locked': False},
                                   {'code': '>>> fourth_product\n39250', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
