test = {   'name': 'q5_2',
    'points': [0, 0],
    'suites': [   {   'cases': [   {   'code': '>>> # Hint: If you are getting 47, you may be computing\n>>> # the biggest change rather than the biggest decrease\n>>> biggest_decrease != 47\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> 30 <= biggest_decrease < 47\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
