test = {   'name': 'q3_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> -1 <= observed_diff_proportion <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # The observed difference in proportion should be about 0.219\n>>> np.round(observed_diff_proportion, 3) == 0.219\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
