test = {   'name': 'q3_6',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> type(farmers_markets_locations_by_longitude) == tables.Table\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> list(farmers_markets_locations_by_longitude.column('x').take(range(3)))\n[-64.704300000000003, -64.778899999999993, -64.879900000000006]",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
