test = {   'name': 'q1_6',
    'points': [0.05, 0.1, 0.1],
    'suites': [   {   'cases': [   {   'code': '>>> pter_over_time.take(0)\nDate       | NEI     | NEI-PTER | Year | PTER\n1994-01-01 | 10.0974 | 11.172   | 1994 | 1.0746',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> pter_over_time.num_rows\n90', 'hidden': False, 'locked': False},
                                   {'code': '>>> pter_over_time.num_columns\n5', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
