test = {   'name': 'q3_4',
    'points': [0, 0, 0, 0],
    'suites': [   {   'cases': [   {'code': ">>> distribution_1 in ['empirical', 'probability']\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> distribution_2 in ['empirical', 'probability']\nTrue", 'hidden': False, 'locked': False},
                                   {'code': '>>> type(player_count_1) == int and type(player_count_2) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(area_total_1) == int and type(area_total_2) == int\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
