test = {   'name': 'q2_2',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> # Check your column labels and spelling\n>>> recent_poverty_total.labels == ('geo', 'poverty_percent', 'population_total', 'poverty_total')\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> # Careful, the population of Australia in 2010 was 22,162,863\n>>> recent_poverty_total.where('geo', 'aus').column(2).item(0)\n22162863",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> float(recent_poverty_total.where('geo', 'aus').column(3).item(0))\n301415.0", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
