test = {   'name': 'q2_1',
    'points': [0, 0],
    'suites': [   {   'cases': [   {   'code': '>>> # Your resample should have the same number of rows as the original sample\n>>> simulate_resample(observations).num_rows\n17',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> simulate_resample(observations).labels[0] == observations.labels[0]\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
